// ************
// MAIN CONTEXT
// ************
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const SET_ALERT = "SET_ALERT ";
const REMOVE_ALERT = "REMOVE_ALERT";

// fetch animals
const FETCH_ANIMALS_BEGIN = "FETCH_ANIMALS_BEGIN";
const FETCH_ANIMALS_SUCCESS = "FETCH_ANIMALS_SUCCESS";
const FETCH_ANIMALS_ERROR = "FETCH_ANIMALS_ERROR";
const FETCH_SINGLE_ANIMAL_BEGIN = "FETCH_SINGLE_ANIMAL_BEGIN";
const FETCH_SINGLE_ANIMAL_SUCCESS = "FETCH_SINGLE_ANIMAL_SUCCESS";
const FETCH_SINGLE_ANIMAL_ERROR = "FETCH_SINGLE_ANIMAL_ERROR";

// fetch news
const FETCH_NEWS_BEGIN = "FETCH_NEWS_BEGIN";
const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR";
const FETCH_SINGLE_NEWS_BEGIN = "FETCH_SINGLENEWS_BEGIN";
const FETCH_SINGLE_NEWS_SUCCESS = "FETCH_SINGLENEWS_SUCCESS";
const FETCH_SINGLE_NEWS_ERROR = "FETCH_SINGLENEWS_ERROR";

// *********************
// ANIMAL FILTER CONTEXT
// *********************
const LOAD_ANIMALS = "LOAD_ANIMALS";
const FILTER_ANIMALS = "FILTER_ANIMALS";
const CLEAR_ANIMAL_FILTERS = "CLEAR_ANIMAL_FILTERS";
const UPDATE_FILTERS = "UPDATE_FILTERS";
const PAGINATE = "PAGINATE";
const CHANGE_PAGE_INDEX = "CHANGE_PAGE_INDEX";

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  SET_ALERT,
  REMOVE_ALERT,
  FETCH_ANIMALS_BEGIN,
  FETCH_ANIMALS_SUCCESS,
  FETCH_ANIMALS_ERROR,
  FETCH_SINGLE_ANIMAL_BEGIN,
  FETCH_SINGLE_ANIMAL_SUCCESS,
  FETCH_SINGLE_ANIMAL_ERROR,
  LOAD_ANIMALS,
  FILTER_ANIMALS,
  CLEAR_ANIMAL_FILTERS,
  FETCH_NEWS_BEGIN,
  FETCH_NEWS_SUCCESS,
  FETCH_NEWS_ERROR,
  FETCH_SINGLE_NEWS_BEGIN,
  FETCH_SINGLE_NEWS_SUCCESS,
  FETCH_SINGLE_NEWS_ERROR,
  UPDATE_FILTERS,
  PAGINATE,
  CHANGE_PAGE_INDEX,
};
